apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab14-deployment
  namespace: lab14-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab14
  template:
    metadata:
      labels:
        app: lab14
    spec:
      containers:
        - name: lab14
          image: tayyabqaisar/latest
          ports:
            - containerPort: 3000
